CREATE TABLE IF NOT EXISTS players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT UNIQUE NOT NULL,
  criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS saves (
  player_id INTEGER PRIMARY KEY,
  evento_atual TEXT,
  energia INTEGER NOT NULL DEFAULT 70,
  reputacao INTEGER NOT NULL DEFAULT 50,
  networking INTEGER NOT NULL DEFAULT 50,
  ansiedade INTEGER NOT NULL DEFAULT 0,
  produtividade INTEGER NOT NULL DEFAULT 50,
  aprendizado INTEGER NOT NULL DEFAULT 50,
  dia_atual INTEGER NOT NULL DEFAULT 1,
  eventos_hoje INTEGER NOT NULL DEFAULT 0,
  flags_json TEXT NOT NULL DEFAULT '{}',
  final_obtido TEXT,
  atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  evento_id TEXT NOT NULL,
  opcao_id TEXT NOT NULL,
  decidido_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ranking_global (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  pontuacao INTEGER NOT NULL,
  final_id TEXT NOT NULL,
  registrado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_decisions_player ON decisions(player_id);
CREATE INDEX IF NOT EXISTS idx_ranking_pontuacao ON ranking_global (pontuacao DESC);
